site_name: VisionAlign-Fracture
site_description: Sistema de Visão Computacional Industrial para Inspeção de Latas
site_author: Victor Silva

theme:
  name: material
  language: pt
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy

plugins:
  - search
  - i18n:
      languages:
        - locale: pt
          name: Português
          default: true
          build: true
          site_name: VisionAlign-Fracture
        - locale: en
          name: English
          build: true
          site_name: VisionAlign-Fracture (EN)

nav:
  - Início: index.md
  - Instalação: installation.md
  - Tecnologias: tecnologias.md
  - Arquitetura: architecture.md
  - Como foi feito: como_foi_feito.md
  - Glossário: glossary.md
  - API e Segurança: api_reference.md
  - Manutenção: maintenance.md
  - Perguntas Frequentes: faqs.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition